package:
  name: fragments
  version: 0.1

source:
  git_url: https://github.com/Clyde-fare/fragments.git
#   path: ../

build:
  number: 0
  
requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
