package:
  name: graph-frags
  version: 0.1

source:
  git_url: https://github.com/Clyde-fare/graph_frags.git

build:
  number: 0
  
requirements:
  build:
    - python
    - setuptools
  run:
    - numpy
    - scipy

test:
  requires:
    - nose
    - ase
    - ase-extensions

  imports:
    - graph_frags


